from __future__ import annotations

CREATED = "CREATED"
LABEL_PRINTED = "LABEL_PRINTED"
COLLECTED = "COLLECTED"
AT_SORTING_HUB = "AT_SORTING_HUB"
IN_TRANSIT = "IN_TRANSIT"
OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY"
DELIVERED = "DELIVERED"
DELIVERY_FAILED = "DELIVERY_FAILED"
RESCHEDULED = "RESCHEDULED"
RETURNED = "RETURNED"

EVENT_TYPES = [
    CREATED,
    LABEL_PRINTED,
    COLLECTED,
    AT_SORTING_HUB,
    IN_TRANSIT,
    OUT_FOR_DELIVERY,
    DELIVERED,
    DELIVERY_FAILED,
    RESCHEDULED,
    RETURNED,
]


PRE_DELIVERY = [CREATED, LABEL_PRINTED, COLLECTED, AT_SORTING_HUB, IN_TRANSIT, OUT_FOR_DELIVERY]


DELIVERY_AREA = {OUT_FOR_DELIVERY, DELIVERED, DELIVERY_FAILED, RESCHEDULED, RETURNED}

TRANSITIONS = {
    CREATED: {LABEL_PRINTED},
    LABEL_PRINTED: {COLLECTED},
    COLLECTED: {AT_SORTING_HUB},
    AT_SORTING_HUB: {IN_TRANSIT},
    IN_TRANSIT: {OUT_FOR_DELIVERY},
    OUT_FOR_DELIVERY: {DELIVERED, DELIVERY_FAILED},
    DELIVERY_FAILED: {RESCHEDULED, RETURNED},
    RESCHEDULED: {OUT_FOR_DELIVERY},
    DELIVERED: set(),
    RETURNED: set(),
}

TERMINAL = {DELIVERED, RETURNED}


def is_valid_transition(src: str, dst: str) -> bool:
    return dst in TRANSITIONS.get(src, set())
